--- 
- 
  connection: local
  gather_facts: false
  hosts: nodos-C
  roles:
   - Juniper.junos

  tasks:

    - 
      template: "src='templates/l3vpn.j2' dest='files/{{inventory_hostname}}_l3vpns.conf'"

    -
      junos_config:
        provider: "{{credentials}}"
        src: "files/{{inventory_hostname}}_l3vpns.conf"
        src_format: text
        comment: 'adding some users'
        host: "{{junos_host}}"
      name: "install users"
