---
loopback: 9.9.9.9
siteid: 9

ldpnhs:
 -
    ip: 3.3.3.3
 -
    ip: 6.6.6.6

vrfs:
 - 
    idvpn: 30
    interfaces: 
      -
        name: ge-0/0/4
        vlan: 300
        lan: 100.2.1.1/24
      -
        name: ge-0/0/5
        vlan: 301
        lan: 100.2.2.1/24
 
 - 
    idvpn: 31
    interfaces:
    -
      name: ge-0/0/4
      vlan: 302
      lan: 200.2.1.1/24


vplss:
 - 
    idvpn: 40
    interfaces: 
      -
        name: ge-0/0/4
        vlan: 400
      -   
        name: ge-0/0/5
        vlan: 401
